package com.codenotfound.entity;

import java.sql.Blob;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "fileUpload")
public class Fileupload {
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	private String id;
	private String documentName;
	@DynamoDBAttribute
	private String documentFor;
	@DynamoDBAttribute
	private String documentHolderName;
	@DynamoDBAttribute
	private String documentCategory;
	@DynamoDBAttribute
	private byte[] documentFile;

	public String getDocumentName() {
		return documentName;
	}

	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}

	public String getDocumentFor() {
		return documentFor;
	}

	public void setDocumentFor(String documentFor) {
		this.documentFor = documentFor;
	}

	public String getDocumentHolderName() {
		return documentHolderName;
	}

	public void setDocumentHolderName(String documentHolderName) {
		this.documentHolderName = documentHolderName;
	}

	public String getDocumentCategory() {
		return documentCategory;
	}

	public void setDocumentCategory(String documentCategory) {
		this.documentCategory = documentCategory;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public byte[] getDocumentFile() {
		return documentFile;
	}

	public void setDocumentFile(byte[] documentFile) {
		this.documentFile = documentFile;
	}



}
