package com.codenotfound.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.codenotfound.dto.ExpenseOnTripBilledDto;
import com.codenotfound.dto.ExpenseonRTOandTOLLDto;

@DynamoDBTable(tableName = "tripRegister")
public class TripRegister {

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	private String id;
	@DynamoDBAttribute
	private String vechileNumber;
	@DynamoDBAttribute
	private String driverName1;
	@DynamoDBAttribute
	private String driverName2;
	@DynamoDBAttribute
	private String cleanerName;
	@DynamoDBAttribute
	private String startPlace;
	@DynamoDBAttribute
	private String endPlace;
	@DynamoDBAttribute
	private BigDecimal vehicleAdvance;
	@DynamoDBAttribute
	private String goodsName;
	@DynamoDBAttribute
	private Integer goodsTotalWeight;
	@DynamoDBAttribute
	private Integer hireprice;
	@DynamoDBAttribute
	private BigDecimal amountpaidonLoad;
	@DynamoDBAttribute
	private BigDecimal amountPaidonOffload;
	@DynamoDBAttribute
	private Integer totalNumberofKM;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = Fuel.class)
	private List<Fuel> fuel;
	@DynamoDBAttribute
	private List<ExpenseOnTripBilledDto> expenseOnTripBilled;
	@DynamoDBAttribute
	private List<ExpenseonRTOandTOLLDto> expenseonRTOandTOLL;
	@DynamoDBAttribute
	private BigDecimal commissionAsBilled;
	@DynamoDBAttribute
	private BigDecimal totalDieselAmount;
	@DynamoDBAttribute
	private BigDecimal totalDriverWageForTrip;
	@DynamoDBAttribute
	private BigDecimal cleanerWage;
	@DynamoDBAttribute
	private BigDecimal totalexpenseonRTOandTOLL;
	@DynamoDBAttribute
	private BigDecimal expenseForLoading;
	@DynamoDBAttribute
	private BigDecimal expenseForunloading;
	@DynamoDBAttribute
	private BigDecimal totalTollExpense;
	@DynamoDBAttribute
	private Integer totalunBilledExpense;
	@DynamoDBAttribute
	private BigDecimal totalExpenseForTrip;
	@DynamoDBAttribute
	private BigDecimal totalIncome;
	@DynamoDBAttribute
	private Integer totalprofitOnTrip;
	@DynamoDBAttribute
	private Date tripStartDate;
	@DynamoDBAttribute
	private Date tripEndDate;
	@DynamoDBAttribute
	private BigDecimal totalBilledExpense;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = Advance.class)
	private List<Advance> advances;
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = AtmCreditDebit.class)
	private List<AtmCreditDebit> atmCreditDebits;
	@DynamoDBAttribute
	private BigDecimal drivertoGive;
	@DynamoDBAttribute
	private BigDecimal otherExpense;
	@DynamoDBAttribute
	private BigDecimal billedtollExpense;
	@DynamoDBAttribute
	private String statusOfTrip;
	
	
	public String getStatusOfTrip() {
		return statusOfTrip;
	}

	public void setStatusOfTrip(String statusOfTrip) {
		this.statusOfTrip = statusOfTrip;
	}

	public BigDecimal getOtherExpense() {
		return otherExpense;
	}

	public void setOtherExpense(BigDecimal otherExpense) {
		this.otherExpense = otherExpense;
	}

	public BigDecimal getBilledtollExpense() {
		return billedtollExpense;
	}

	public void setBilledtollExpense(BigDecimal billedtollExpense) {
		this.billedtollExpense = billedtollExpense;
	}

	public List<AtmCreditDebit> getAtmCreditDebits() {
		if (atmCreditDebits == null) {
			atmCreditDebits = new ArrayList<>();
		}
		return atmCreditDebits;
	}

	public void setAtmCreditDebits(List<AtmCreditDebit> atmCreditDebits) {
		this.atmCreditDebits = atmCreditDebits;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<Advance> getAdvances() {
		if (advances == null) {
			advances = new ArrayList<>();
		}
		return advances;
	}

	public BigDecimal getDrivertoGive() {
		return drivertoGive;
	}

	public void setDrivertoGive(BigDecimal drivertoGive) {
		this.drivertoGive = drivertoGive;
	}

	public void setAdvances(List<Advance> advances) {
		this.advances = advances;
	}

	public BigDecimal getTotalBilledExpense() {
		return totalBilledExpense;
	}

	public void setTotalBilledExpense(BigDecimal totalBilledExpense) {
		this.totalBilledExpense = totalBilledExpense;
	}

	public Date getTripStartDate() {
		return tripStartDate;
	}

	public void setTripStartDate(Date tripStartDate) {
		this.tripStartDate = tripStartDate;
	}

	public Date getTripEndDate() {
		return tripEndDate;
	}

	public void setTripEndDate(Date tripEndDate) {
		this.tripEndDate = tripEndDate;
	}

	public String getVechileNumber() {
		return vechileNumber;
	}

	public void setVechileNumber(String vechileNumber) {
		this.vechileNumber = vechileNumber;
	}

	public String getDriverName1() {
		return driverName1;
	}

	public void setDriverName1(String driverName1) {
		this.driverName1 = driverName1;
	}

	public String getDriverName2() {
		return driverName2;
	}

	public void setDriverName2(String driverName2) {
		this.driverName2 = driverName2;
	}

	public String getCleanerName() {
		return cleanerName;
	}

	public void setCleanerName(String cleanerName) {
		this.cleanerName = cleanerName;
	}

	public String getStartPlace() {
		return startPlace;
	}

	public void setStartPlace(String startPlace) {
		this.startPlace = startPlace;
	}

	public String getEndPlace() {
		return endPlace;
	}

	public void setEndPlace(String endPlace) {
		this.endPlace = endPlace;
	}

	public BigDecimal getVehicleAdvance() {
		return vehicleAdvance;
	}

	public void setVehicleAdvance(BigDecimal vehicleAdvance) {
		this.vehicleAdvance = vehicleAdvance;
	}

	public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public Integer getGoodsTotalWeight() {
		return goodsTotalWeight;
	}

	public void setGoodsTotalWeight(Integer goodsTotalWeight) {
		this.goodsTotalWeight = goodsTotalWeight;
	}

	public Integer getHireprice() {
		return hireprice;
	}

	public void setHireprice(Integer hireprice) {
		this.hireprice = hireprice;
	}

	public BigDecimal getAmountpaidonLoad() {
		return amountpaidonLoad;
	}

	public void setAmountpaidonLoad(BigDecimal amountpaidonLoad) {
		this.amountpaidonLoad = amountpaidonLoad;
	}

	public BigDecimal getAmountPaidonOffload() {
		return amountPaidonOffload;
	}

	public void setAmountPaidonOffload(BigDecimal amountPaidonOffload) {
		this.amountPaidonOffload = amountPaidonOffload;
	}

	public Integer getTotalNumberofKM() {
		return totalNumberofKM;
	}

	public void setTotalNumberofKM(Integer totalNumberofKM) {
		this.totalNumberofKM = totalNumberofKM;
	}

	public List<Fuel> getFuel() {
		if (fuel == null) {
			fuel = new ArrayList<>();
		}
		return fuel;
	}

	public void setFuel(List<Fuel> fuel) {
		this.fuel = fuel;
	}

	public List<ExpenseOnTripBilledDto> getExpenseOnTripBilled() {
		return expenseOnTripBilled;
	}

	public void setExpenseOnTripBilled(List<ExpenseOnTripBilledDto> expenseOnTripBilled) {
		this.expenseOnTripBilled = expenseOnTripBilled;
	}

	public List<ExpenseonRTOandTOLLDto> getExpenseonRTOandTOLL() {
		return expenseonRTOandTOLL;
	}

	public void setExpenseonRTOandTOLL(List<ExpenseonRTOandTOLLDto> expenseonRTOandTOLL) {
		this.expenseonRTOandTOLL = expenseonRTOandTOLL;
	}

	public BigDecimal getCommissionAsBilled() {
		return commissionAsBilled;
	}

	public void setCommissionAsBilled(BigDecimal commissionAsBilled) {
		this.commissionAsBilled = commissionAsBilled;
	}

	public BigDecimal getTotalDieselAmount() {
		return totalDieselAmount;
	}

	public void setTotalDieselAmount(BigDecimal totalDieselAmount) {
		this.totalDieselAmount = totalDieselAmount;
	}

	public BigDecimal getTotalDriverWageForTrip() {
		return totalDriverWageForTrip;
	}

	public void setTotalDriverWageForTrip(BigDecimal totalDriverWageForTrip) {
		this.totalDriverWageForTrip = totalDriverWageForTrip;
	}

	public BigDecimal getCleanerWage() {
		return cleanerWage;
	}

	public void setCleanerWage(BigDecimal cleanerWage) {
		this.cleanerWage = cleanerWage;
	}

	public BigDecimal getTotalexpenseonRTOandTOLL() {
		return totalexpenseonRTOandTOLL;
	}

	public void setTotalexpenseonRTOandTOLL(BigDecimal totalexpenseonRTOandTOLL) {
		this.totalexpenseonRTOandTOLL = totalexpenseonRTOandTOLL;
	}

	public BigDecimal getExpenseForLoading() {
		return expenseForLoading;
	}

	public void setExpenseForLoading(BigDecimal expenseForLoading) {
		this.expenseForLoading = expenseForLoading;
	}

	public BigDecimal getExpenseForunloading() {
		return expenseForunloading;
	}

	public void setExpenseForunloading(BigDecimal expenseForunloading) {
		this.expenseForunloading = expenseForunloading;
	}

	public BigDecimal getTotalTollExpense() {
		return totalTollExpense;
	}

	public void setTotalTollExpense(BigDecimal totalTollExpense) {
		this.totalTollExpense = totalTollExpense;
	}

	public Integer getTotalunBilledExpense() {
		return totalunBilledExpense;
	}

	public void setTotalunBilledExpense(Integer totalunBilledExpense) {
		this.totalunBilledExpense = totalunBilledExpense;
	}

	public BigDecimal getTotalExpenseForTrip() {
		return totalExpenseForTrip;
	}

	public void setTotalExpenseForTrip(BigDecimal totalExpenseForTrip) {
		this.totalExpenseForTrip = totalExpenseForTrip;
	}

	public BigDecimal getTotalIncome() {
		return totalIncome;
	}

	public void setTotalIncome(BigDecimal totalIncome) {
		this.totalIncome = totalIncome;
	}

	public Integer getTotalprofitOnTrip() {
		return totalprofitOnTrip;
	}

	public void setTotalprofitOnTrip(Integer totalprofitOnTrip) {
		this.totalprofitOnTrip = totalprofitOnTrip;
	}

}
